language: python
python:
-   "2.7"
-   "3.3"
-   "3.4"
-   "3.5"
-   "3.6"
install:
- pip install -r requirements/testing.txt
script:
- tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
- coverage run -m pytest
- coverage report -m
after_success:
  - coveralls
